"""convert user id to string

Revision ID: 68d3359b7845
Revises: 998d15dc6b7e
Create Date: 2025-09-30 07:49:01.075237

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68d3359b7845"
down_revision: str | None = "998d15dc6b7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "id", existing_type=sa.UUID(), type_=sa.String(length=36), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "id", existing_type=sa.String(length=36), type_=sa.UUID(), existing_nullable=False)
    # ### end Alembic commands ###
