"""add_account_relationship_to_users

Revision ID: 8346c8e07917
Revises: e5fcd6d2d9ff
Create Date: 2026-02-08 01:09:31.051654

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8346c8e07917"
down_revision: str | None = "e5fcd6d2d9ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "users", "accounts", ["id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    # ### end Alembic commands ###
