name: Pass checks and tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          make install
      - name: Check style, format and lint
        run: |
          make check-typing
          make check-format
          make check-lint
      - name: Tests
        run: |
          make test

  version-changelog:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CODENET_TOKEN }}
          fetch-depth: 0
      - name: Bump version and update changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.CODENET_TOKEN }}