name: Bump version and generate CHANGELOG

on:
  workflow_dispatch:


jobs:
  semantic_release:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CODENET_TOKEN }}
          fetch-depth: 0
      - name: Bump version and update changelog
        uses: python-semantic-release/python-semantic-release@master
        with:
          build: false
          push: true
          changelog: true
          commit: true
          tag: true
          vcs_release: false
          config_file: pyproject.toml
          github_token: ${{ secrets.CODENET_TOKEN }}