name: Bump version and generate CHANGELOG

on:
  workflow_dispatch:


jobs:
  semantic_release:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🛡️ Harden runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: 📥 Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Bump version and update changelog
        uses: python-semantic-release/python-semantic-release@9a026e9303981c866c3425723009becb2437c757 # v10.0.2
        with:
          build: false
          push: true
          changelog: true
          commit: true
          tag: true
          vcs_release: false
          config_file: pyproject.toml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_email: ${{ vars.GIT_COMMITTER_EMAIL }}
          git_committer_name: ${{ vars.GIT_COMMITTER_NAME }}
          ssh_public_signing_key: ${{ vars.SSH_PUBLIC_SIGNING_KEY }}
          ssh_private_signing_key: ${{ secrets.SSH_PRIVATE_SIGNING_KEY }}